name: yumemi_coding_test
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0
  provider: ^6.1.4 
  flutter_dotenv: ^5.2.1

  flutter_localization: ^0.3.2

  flutter_localizations:
    sdk: flutter  
  intl: "^0.19.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    #- lib/l10n
    - assets/not_found.png

